### ISSUE TITLE
Flesh Out Events

### ISSUE THREAD

**Issue by rohan-nittur** [rohan-nittur/ProgSoc-Website#7]
Consider adding an *Internship Preparation Workshop* to get more people involved with the society.

Also add one (for now) example of one of the (monthly?!) events we are planning to run, i.e. *Introduction to ML for Complete Beginners*

**Comment by perryliuofficial** [comment]
Prioritise implementing new filters to support a barrage of regular events that can be filtered out https://github.com/rohan-nittur/ProgSoc-Website/issues/8

**Comment by perryliuofficial** [comment]
Update: new filter system now in place, ready for #7 to proceed
